version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
    env_file:
      - .env
  mysql-container:
    image: mysql
    volumes:
      - /Users/huangqiang/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=travel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3307"
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/huangqiang/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge