-- AlterTable
ALTER TABLE `Article` MODIFY `updateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` MODIFY `updateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
